# Generated by Django 2.2.6 on 2019-10-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(max_length=200)),
                ('tipoModelo', models.CharField(max_length=200)),
                ('idModelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePiloto', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField()),
                ('fechnac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNave', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateField()),
                ('idNave', models.CharField(max_length=200)),
                ('Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionNaves.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='DueñoNave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechAdquisicion', models.DateTimeField(auto_now_add=True)),
                ('Nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionNaves.Nave')),
                ('Piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionNaves.Piloto')),
            ],
        ),
    ]
