# Generated by Django 2.2.6 on 2019-11-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionNaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nave',
            name='fotoNave',
            field=models.ImageField(default='static/img', upload_to='img'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='fotoPiloto',
            field=models.ImageField(default='static/img', upload_to='img'),
        ),
    ]
