# Generated by Django 2.2.6 on 2019-11-19 01:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionNaves', '0002_auto_20191117_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='body',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nave',
            name='fotoNave',
            field=models.ImageField(default='static/img', upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='fotoPiloto',
            field=models.ImageField(default='static/img', upload_to='static/img'),
        ),
    ]
