# Generated by Django 2.2.6 on 2019-11-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionNaves', '0003_auto_20191118_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='body',
        ),
    ]
